### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by SamGG** [KlugerLab/oocPCA#1]
Hi,
I wanted to try oocPCA under Win7x64, R 351, but I got the following error. May be my R install is corrupted, but I reinstalled a github R package without error.
Best.
```
> devtools::install_github("KlugerLab/oocPCA")
Error: HTTP error 404.
  Not Found

  Rate limit remaining: 48/60
  Rate limit reset at: 2018-11-12 11:04:17 UTC
```

**Comment by linqiaozhi** [comment]
Thanks for the issue report!

It should be

`devtools::install_github("KlugerLab/oocPCA/oocRPCA")`

So we need to fix that in the README.

However, the command you were using did not give me a 404, rather it gave me a "no DESCRIPTION" error. So, please let me know if this does not fix it for you!

**Comment by SamGG** [comment]
Hi George!
Installed smoothly now.
Thanks.
